apiVersion: batch/v1
kind: Job
metadata:
  name: image-scan
spec:
  template:
    metadata:
      labels:
        app: image-scan
    spec:
      containers:
        - name: image-scan
          image: docker.io/aquasec/trivy
          command:
            - trivy
          args:
            - '--insecure'
            - '--severity'
            - 'HIGH,CRITICAL'
            - '--exit-code'
            - '1'
            - '--remote'
            - 'http://trivy-rules:8088'
            - '871065065486.dkr.ecr.us-east-2.amazonaws.com/jenkinsflask'
      restartPolicy: Never
  backoffLimit: 0
